FROM node:slim

RUN mkdir -p /usr/src
WORKDIR /usr/src

# Install app dependencies
COPY package.json /usr/src/
RUN npm install --only=production

ARG env
ENV ENV=$env

CMD ["node", "app/bin/server.js"]